dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
        - mkdir build
        - cd build
        - cmake --build .. -- VERBOSE=1

script:
        - make 
